### PR TITLE
[24.1] Backport: Better handling of MANIFEST.MF attributes

### PR DESCRIPTION
**Pull request by zakkak**
Backport of https://github.com/graalvm/mandrel-packaging/pull/435

> Previously, the build script would add these two attributes irrespective
> whether or not they'd exist in the Graal artefacts:
> 
>   Specification-Version
>   Implementation-Version
> 
> With this patch, only updates to the Implementation-Version attribute
> are done based on the maven version in use. Specification-Version is
> only added if it's not yet there in a jar or source jar file.

(cherry picked from commit 48c154e09da76394c09f3ed9b1ae03ed699d0df5)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]

**Comment by zakkak** [comment]
CI failures should be fixed by https://github.com/oracle/graal/pull/9315 I will update mandrel/24.1 and rerun

**Comment by zakkak** [comment]
Now we get a different error:

```
/usr/bin/ld: hellostrict.o:(.data+0x60): undefined reference to `svm_container_physical_memory'
/usr/bin/ld: hellostrict.o:(.data+0x158): undefined reference to `svm_container_active_processor_count'
/usr/bin/ld: hellostrict.o:(.data+0x528): undefined reference to `svm_container_initialize'
collect2: error: ld returned 1 exit status
```

It looks like `mandrel/24.1` with JDK 23+31 is broken (but not yet caught by the CI which runs on a weekly manner)

**Comment by jerboaa** [comment]
> /usr/bin/ld: hellostrict.o:(.data+0x60): undefined reference to `svm_container_physical_memory'
> /usr/bin/ld: hellostrict.o:(.data+0x158): undefined reference to `svm_container_active_processor_count'
> /usr/bin/ld: hellostrict.o:(.data+0x528): undefined reference to `svm_container_initialize'
> collect2: error: ld returned 1 exit status

This would be fixed by a backport of https://github.com/graalvm/mandrel-packaging/pull/430

**Comment by jerboaa** [comment]
> It looks like `mandrel/24.1` with JDK 23+31 is broken (but not yet caught by the CI which runs on a weekly manner)

Unfortunately, yes. Not sure if we should test 24.1 nightly?

**Comment by zakkak** [comment]
> > It looks like `mandrel/24.1` with JDK 23+31 is broken (but not yet caught by the CI which runs on a weekly manner)
> 
> Unfortunately, yes. Not sure if we should test 24.1 nightly?

Things are not moving that fast there, IMHO running once a week (plus on the manual syncs I do with upstream) is OK.

**Comment by jerboaa** [comment]
> > > It looks like `mandrel/24.1` with JDK 23+31 is broken (but not yet caught by the CI which runs on a weekly manner)
> > 
> > 
> > Unfortunately, yes. Not sure if we should test 24.1 nightly?
> 
> Things are not moving that fast there, IMHO running once a week (plus on the manual syncs I do with upstream) is OK.

OK.

**Comment by zakkak** [comment]
> This would be fixed by a backport of #430

Apparently the CI pipeline was still trying to build `graal/master`.

**Comment by jerboaa** [comment]
> > This would be fixed by a backport of #430
> 
> Apparently the CI pipeline was still trying to build `graal/master`.

Ah, makes sense.
